pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.7-adoptopenjdk-21' }
      }
      steps {
        sh 'mvn --version'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:18-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
  }
}
